= Datensparsam.de & the Principle of Data Economy
:hp-alt-title: principle of data economy
:published_at: 2013-05-21
:hp-tags: python, django, open source

With link:https://www.datensparsam.de[Datensparsam.de] I recently established Germany's first and only civic app focussing on the principle of data economy. The form generator helps people to easily opt out at their registration offices. Here I'd like to write some words about the hows and whys that led to the final web app...

== Data Economy at Registration Offices

Internationally, Germany is often referred to as a country full of strong privacy groups and citizens having some kind of a generic bias against all kinds of _post privacy_ and private data liberality. Nevertheless, there is a huge lack of privacy thinking in one of Germany's official laws: The *compulsory registration* and the communal system of registration!

The problem I see is that registration offices in Germany often sell the private datasets of their citizens to address traders and political parties, companies or further interested parties. In my eyes that's in fact a scandal!

=== Opt-Out at Registration Offices

However, the Federal Republic of Germany wouldn't be a democratic republic without any chance of raising an objection. In fact, German citizens are legally allowed to opt out at their local, communal registration offices, but of course this (for some people) is quite an obstacle.

To simplify the process and the flatten possible obstacles, I created link:https://www.datensparsam.de[Datensparsam.de]. Inspired by Chaos Computer Club Mainz/ Wiesbaden and their post on the link:http://www.cccmz.de/datensparsamkeit/[principle of data economy], I started working on this project during the international link:http://www.openeverything.eu/open-data-day-2013/[Open Data Hackday] 2013 in Berlin.

=== Python, Django, Tastypie

After discussing several possible ways of implementing such an form generator, I came up with a somehow classic technology stack using the link:https://www.djangoproject.com/[Django web-framework] for Python, link:https://github.com/toastdriven/django-tastypie[Tastypie] for a clean and simple API and link:http://twitter.github.io/bootstrap/index.html[Bootstrap] for the frontend.

In the end, the entire technology thing was not the central problem. Much harder was to find, scrape, combine and clean the required data about zipcodes and registration office addresses. The reason for that is, that there (still) are no central/ offical platforms in Germany providing all official addresses or datasets about the n2m relations between zipcodes and municipalities.

Working on link:https://www.datensparsam.de[Datensparsam.de] showed me that there's a strong need of open governmental data in Germany. So hands on and free data!
