= Evolution of a Microservice
:published_at: 2016-01-18
:hp-tags: backend, web development
:hp-alt-title: microservice evolution

Following the common pendulum theorie, every tech debate oscillates between at least two currently trending topics. The same is true when it comes to micro-services (vs. integrated systems). My team at ImmobilienScout24.de (currently) follows a radical micro-services approach, favouring the benefits of smallest possible deployment units over integration (and its advantages). Why and how we chose to do so, I'm going to explain in more detail...

== Microservices, Self-contained Systems & Integrated Applications

At ImmobilienScout24.de my team is responsible for parts of one of our core insertion flows. With thousands of customers-to-be every day and direct business impact, we not just need to be reliable as well as always up-and-running, but also fairly flexible and (even more important) fast, allowing product improvements, bug fixes and multi-variant tests to be rolled out in near-realtime. Helping us to achieve those goals are our continuous live deployment (CLD) infrastructure as well as our near-realtime monitoring and alarming and most imporatantly our constantly evolving, stateless micro-services...

The micro-service architecture I am refering to in this article is the probably most remote antipole of what is commonly known as integrated system (or what some companies call legacy, heritage or mothership). Between those two extrema, there is a whole bunch of manifestations, variations and adoptions like the so-called link:http://scs-architecture.org/index.html[Self-contained System] (SCS) architecture. However, I am usually not a big fan of some middle courses as in my experience they often combine not the intended advantages but the downsides of two radical different ideas. Furthermore, if a framework (and an architecture is nothing else) allows people to implement their first gut feelings instead of understanding the greater ideas, concepts and reasons, they tend to do so. In my eyes, sticking with and optimizing your infrastructure for one clean approach (not in a religious but explaining manner) generally helps creating easy repeatable and comprehensible software architecture - as long as you can handle possible drawbacks.

video::moNJBBm7avM[youtube]


One of the drawbacks of following the micro-services approach is that you need to cut. Whether you cut it functional or by following business use-cases - You need to cut. It's a drawback, becuase every software tends to grow bigger - it's just a question of time when a single-purpose micro-service becomes a multi-purpose legacy app. There's no way to prevent your software from doing so. You have no other chance than to be fully-aware of that fact, and to cut carefully and (most importantly) often. 

