= Evolution of a Microservice
:published_at: 2016-01-18
:hp-tags: backend, web development
:hp-alt-title: microservice evolution

Following the common pendulum theorie, every tech debate oscillates between at least two currently trending topics. The same is true when it comes to micro-services vs. integrated systems. My team at ImmobilienScout24.de (currently) follows a radical micro-services approach, favouring the benefits of smallest possible deployment units over integration (and its advantages). Why and how we chose to do so, I'm going to explain in more detail...

== Microservices, Self-contained Systems & Integrated Applications

The micro-service architecture I am refering to in this article is the antipole of what is commonly known as integrated system. Between those two extrema, there is a whole bunch of manifestations, variations and adoptions like the so-called link:http://scs-architecture.org/index.html[Self-contained System] (SCS) architecture. However, I am usually not a big fan of some middle courses as in my experience they combine the downsides of both radical different ideas. In my eyes, sticking with and optimizing for one clean approach generally helps - as long as you can handle possible drawbacks.



video::moNJBBm7avM[youtube]